apiVersion: v1
kind: Pod
metadata:
 name: nginx-pod
spec:
 containers:
   - name: nginx-container
     image: nginx
     ports:
       - containerPort: 80
     resources:
       requests:
         cpu: "100m"
         memory: "128Mi"
       limits:
         cpu: "500m"
         memory: "256Mi"


   - name: python
     image: python
     command: ["sleep", "3600"]  
     resources:
       requests:
         cpu: "50m"
         memory: "64Mi"
       limits:
         cpu: "200m"
         memory: "128Mi"
